# Generated by Django 5.0.4 on 2024-12-19 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
